source 'https://github.com/CocoaPods/Specs.git'
target 'zenly' do
  pod 'PhoneNumberKit'
  pod 'GoogleMaps'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
end

workspace 'zenly'